kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pulumi
networking:
  apiServerPort: 6443
  apiServerAddress: "0.0.0.0"
  serviceSubnet: "10.12.0.0/16"
  podSubnet: "10.242.0.0/16"
  ######################################################################
  # The following is required for cilium to work with kind
  disableDefaultCNI: true # disable kindnet
  kubeProxyMode: none # disable kube-proxy
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2
    extraMounts: # Persistent image cache
      - hostPath: /var/lib/docker/volumes/pulumi-control-plane-n01/_data
        containerPath: /var/lib/containerd
  - role: worker
    image: kindest/node:v1.29.2
    extraMounts: # Persistent image cache
      - hostPath: /var/lib/docker/volumes/pulumi-worker-n01/_data
        containerPath: /var/lib/containerd
  - role: worker
    image: kindest/node:v1.29.2
    extraMounts: # Persistent image cache
      - hostPath: /var/lib/docker/volumes/pulumi-worker-n02/_data
        containerPath: /var/lib/containerd
    # Expose ports on the host:
    # - 2022/tcp
    # - 8080/tcp
    # - 8443/tcp
    extraPortMappings:
      - listenAddress: "0.0.0.0"
        protocol: TCP
        hostPort: 8080
        containerPort: 80
      - listenAddress: "0.0.0.0"
        protocol: TCP
        hostPort: 8443
        containerPort: 443
      - listenAddress: "0.0.0.0"
        protocol: TCP
        hostPort: 2022
        containerPort: 22
    kubeadmConfigPatches:
      - |
        # Label the worker node listening on service ports
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
